### ISSUE TITLE
Don't mark strings as translatable

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-notifications#18]
The jinja template resolution is already supporting `locale`, see [here](https://github.com/inveniosoftware/invenio-notifications/blob/master/invenio_notifications/backends/utils/loaders.py#L37). The default templates should not add `_(` translatable strings.

**Comment by rekt-hard** [comment]
Adding translatable strings in the templates allows to ship InvenioRDM with notifications translated in different languages. If translations are provided, every institution using a certain language will profit. If we do not include translations, each institution will have to provide their own templates for each language they use.

The resolution taking locale and backend id into account is still great, if there shall be differences in the notification content for specific languages or backends (or a certain combination).

In my opinion, we do not loose anything if we mark template content as translatable but rather move towards a more complete product without the **need** to customize each instance (still possible though if required).

**Comment by ntarocco** [comment]
> 

Don't get me wrong, I fully agree that we should be able to translate the notifications messages. However, it doesn't make much sense to me to mark each string is translatable, as the full content of the template will be VERY different in each instance, very customized.
I doubt that anyone would want to use this default style: there is always a footer, often a header, and extra info.
We should allows overriding the entire template per language.

**Comment by lnielsen** [comment]
Discussed in IRL at InvenioRDM Workshop 2024 and decided to close issue. Email templates are now in a good shape and thus it makes sense to have translatable strings.
