### ISSUE TITLE
add no-reply sender address configuration

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-notifications#19]
As noticed on user support, the users have a habit of replying on the system generated e-mails, therefore we need a configuration a common no-reply email address for the notifications sent by the module

**Comment by rekt-hard** [comment]
The linked PR would allow to set an explicit `reply_to` attribute of the mail, which e-mail clients should respect.
In order to set the sender of all e-mails `MAIL_DEFAULT_SENDER` can be configured.

**Comment by zzacharo** [comment]
> 


> The linked PR would allow to set an explicit `reply_to` attribute of the mail, which e-mail clients should respect. In order to set the sender of all e-mails `MAIL_DEFAULT_SENDER` can be configured.

If you set the `MAIL_DEFAULT_SENDER`, would that precede your new config variable?

**Comment by rekt-hard** [comment]
The mail sender is always `MAIL_DEFAULT_SENDER`. This is only for the reply to attribute of the email.
